### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by heidipowers** [gabergg/react-scrollable-anchor#1]
Hey Gabe - thanks so much for this scroller! I wanted to let you know I had an error on install of the react-scrollable-anchor when I tried to import to the component. 

    Failed to compile.

    Error in ./~/react-scrollable-anchor/~/react-dom/index.js
    Module not found: 'react/lib/ReactDOM' in  /Users/Heidi/Desktop/hp-portfolio/node_modules/react-scrollable-anchor/node_modules/react-dom

    @ ./~/react-scrollable-anchor/~/react-dom/index.js 3:17-46

I changed 
`module.exports = require('react/lib/ReactDOM');`

 to 
`module.exports = require('react-dom/lib/ReactDOM');`

and it started up without a problem. I used the `react-create-app` command for this project if that makes a difference. Thanks again!

**Comment by gabergg** [comment]
Hey Heidi, thanks for reporting this. It was an issue of peer dependencies. If you update to v0.4.1 (or even v0.4.0), the import should work for you. I tested with create-react-app, and all looked good. Please let me know if that doesn't fix it for you.

**Comment by gabergg** [comment]
Fixed in https://github.com/gabergg/react-scrollable-anchor/commit/2b4560a3d8989db6b3cc2be621621d4c5639f3cb
