### ISSUE TITLE
Deprecated React.PropTypes

### ISSUE THREAD

**Issue by v0lume** [gabergg/react-scrollable-anchor#16]
Hi there! 
Every call on site i see lowWarning about using deprecated React.PropTypes in my browser console. Can u remove it and use PropTypes directly from npm package?

![image](https://user-images.githubusercontent.com/5075100/28278965-9e1e3218-6b27-11e7-8309-9c809398ea76.png)

Thanks

**Comment by gabergg** [comment]
Thanks for reporting. Merged the fix.
