### ISSUE TITLE
PropTypes

### ISSUE THREAD

**Issue by CP-Ricardo** [gabergg/react-scrollable-anchor#18]
Hey guys,

whenever installing react-scrollable-anchor from npm directory I never get the fixed version with PropTypes package

**Comment by gabergg** [comment]
Ah, I'll bump npm version tonight, n then you should be good.

**Comment by jorgecuesta** [comment]
Hi still on npm same version with PropTypes warning. Some update? @gabergg

**Comment by gabergg** [comment]
@jorgecuesta should be good now! On 0.5.0.
