### ISSUE TITLE
Invalid prop `id` of type `number`

### ISSUE THREAD

**Issue by Resmedia** [gabergg/react-scrollable-anchor#38]
Hello! 

My project React version: 15.6.2

Some time i have mistake: 

> Invalid prop **id** of type **number** supplied to **ScrollableAnchor**, expected **string**.

What can i do with this?

**Comment by gabergg** [comment]
`ScrollableAnchor` expects its `id` prop to be a string. If you're doing something like `<ScrollableAnchor id={1}>`, you'll need to change it to `<ScrollableAnchor id={'1'}>`.

**Comment by Resmedia** [comment]
Tank's i do it like this and it's OK 

`<ScrollableAnchor  id={'${step.label}'}>`
