### ISSUE TITLE
Doesn't work on  IE9

### ISSUE THREAD

**Issue by flyingalex** [gabergg/react-scrollable-anchor#7]
It works well on Firefox, chrome, IE10, IE11, Edge, except  IE9, anyone has any ideas for this? Thanks in advance.

**Comment by gabergg** [comment]
So, react-scrollable-anchor depends on jump.js, which relies on requestAnimationFrame. I also use history.replaceState in the hash utils. These two functions aren't supported in IE10. Therefore, the package doesn't support IE9 out of the box, and I'd prefer not to include polyfills in the package. I believe if you polyfill these, you would be good to go on IE9!
